---
{{- $namespace := (trimPrefix "*Tpl" .Receiver | lower) }}
order: {{ order }}
title: {{ $namespace }}.{{ .Name }}
---
<!-- Generated by tools/docgen. DO NOT EDIT. -->

{{- define "body" -}}
{{- range . -}}
	{{- if eq .Kind "text" -}}
    {{- if contains "**NOTE**:" .Text -}}
      > {{ wrap 72 .Text | replace "**NOTE**:" "[!NOTE]\n>" }}
    {{- else }}
		  {{- wrap 72 .Text -}}
    {{- end }}
	{{- else if eq .Kind "rawText" -}}
		{{- .Text -}}
	{{- else if eq .Kind "autolink" -}}
		{{- .Text -}}
	{{- else if eq .Kind "link" -}}
		{{- link (escape .Text) .URL -}}
	{{- end -}}
{{- end -}}
{{- end }}

# {{ $namespace }}.{{ .Name }}

{{ range (iter .Doc.Blocks) }}
	{{- if eq .Entry.Kind "paragraph" }}
{{- include "body" .Entry.Spans }}
	{{- else if eq .Entry.Kind "code" }}
{{- codeBlock "go" (include "text" .Entry.Spans) }}
	{{- end }}

{{ end -}}
