# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2
project_name: stencil

# Reproducible builds.
gomod:
  proxy: true
report_sizes: true
metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

builds:
  - main: ./cmd/{{ .ProjectName }}
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X "go.rgst.io/stencil/internal/version.Version={{.Version}}"
    env:
      - CGO_ENABLED=0
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - ppc64
    goos:
      - linux
      - darwin
      - windows
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
    mod_timestamp: "{{ .CommitTimestamp }}"
archives:
  - format: tar.xz
    format_overrides:
      - format: zip
        goos: windows
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: git
  filters:
    exclude:
      - "^test:"
      - "^chore:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: "^.*(feat|chore|fix)\\(deps\\)*:+.*$"
      order: 300
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: "Documentation updates"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: Other work
      order: 9999

# ---------- Packaging
notarize:
  macos:
    - enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'
      sign:
        certificate: "{{.Env.MACOS_SIGN_P12}}"
        password: "{{.Env.MACOS_SIGN_PASSWORD}}"
      notarize:
        issuer_id: "{{.Env.MACOS_NOTARY_ISSUER_ID}}"
        key_id: "{{.Env.MACOS_NOTARY_KEY_ID}}"
        key: "{{.Env.MACOS_NOTARY_KEY}}"

brews:
  - commit_author:
      name: GitHub Actions
      email: 41898282+github-actions[bot]@users.noreply.github.com
    homepage: https://stencil.rgst.io
    license: Apache-2.0
    description: "A modern living-template engine for evolving repositories"
    dependencies:
      - name: git
        os: mac
    conflicts:
      - stencil
    repository:
      owner: rgst-io
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN}}"
nfpms:
  - id: packages
    homepage: https://stencil.rgst.io
    description: |-
      A modern living-template engine for evolving repositories.
    maintainer: Jared Allard <jared@rgst.io>
    license: MIT
    vendor: rgst
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/stencil/copyright
        file_info:
          mode: 0644
    formats:
      - apk
      - deb
      - rpm
    dependencies:
      - git
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

# ---------- Release
sboms:
  - artifacts: archive

release:
  extra_files:
    - glob: .dist/stencil-*-deps.tar.xz
  footer: |-
    **Full Changelog**: https://github.com/rgst-io/stencil/compare/{{ .PreviousTag }}...{{ .Tag }}
