{{- $root := . }}
{{- $args := list -}}
{{- range $name, $_ := .Arguments }}
{{- $args = append $args $name }}
{{- end }}
{{- $args = sortAlpha $args }}
<!-- Generated by 'stencil module gen-args'. DO NOT EDIT. -->
# Arguments
{{ range $name := $args }}
- [{{ $name }}](#{{ $name }})
{{- end }}

## Manifest Arguments

{{- range $name := $args }}
{{- $val := index $root.Arguments $name }}
{{- if $val.From }}
{{- continue }}
{{- end }}

### `{{ $name }}`

{{- if $val.Required }}

**Required**
{{- end }}
{{- if $val.Schema.type }}

**Type**: `{{ $val.Schema.type }}`
{{- else if $val.Schema }}

**Schema**:

```json
{{ $val.Schema | toPrettyJson }}
```
{{- end }}

{{- if $val.Default }}

**Default**: `{{ $val.Default }}`
{{- end }}

{{- if $val.Description }}

{{ $val.Description }}
{{- end }}

{{- end }}

## Shared Arguments

The following arguments are exposed by dependencies that this module
consumes.

{{- range $name := $args }}
{{- $val := index $root.Arguments $name }}
{{- if not $val.From }}
{{- continue }}
{{- end }}

### `{{ $name }}`

**From**: https://{{ $val.From }}

{{- if $val.Description }}

{{ $val.Description }}
{{- end }}

{{- end }}
