#!/usr/bin/env bash
# mise description="Creates a CHANGELOG.md file for the current git tag"
set -euo pipefail

# Get the current tag that we're on.
CURRENT_TAG=$(git describe --tags --abbrev=0)

args=("mise" "run" "changelog" "--")

# If we're on a non-rc version, use the current tag, otherwise use
# unreleased.
if [[ $CURRENT_TAG == *"-rc"* ]]; then
  args+=("--unreleased")
else
  args+=("--current")
fi

# Run mise to generate the changelog.
"${args[@]}"

# If we're on a rc version, fix the header.
if [[ $CURRENT_TAG == *"-rc"* ]]; then
  sed -i.bak "s/^## [unreleased]/## $CURRENT_TAG/" CHANGELOG.md
  rm CHANGELOG.md.bak
fi
