#!/usr/bin/env bash
set -eo pipefail

export AWS_REGION=auto
export AWS_ENDPOINT_URL=https://c41358b3e2e8f5345933f0d433e3abef.r2.cloudflarestorage.com

if [[ -z "${AWS_ACCESS_KEY_ID}" ]]; then
  echo "Using AWS credentials from 1Password" >&2

  export AWS_ACCESS_KEY_ID=$(op item get --vault Stencil "Cloudflare R2 (docs)" --fields "AWS_ACCESS_KEY_ID")
  export AWS_SECRET_ACCESS_KEY=$(op item get --vault Stencil "Cloudflare R2 (docs)" --fields "AWS_SECRET_ACCESS_KEY")

  if [[ -z "${AWS_ACCESS_KEY_ID}" ]] || [[ -z "${AWS_SECRET_ACCESS_KEY}" ]]; then
    echo "Failed to retrieve AWS credentials from 1Password"
    exit 1
  fi
fi

bun run docs:build

if [ $((RANDOM % 30)) -eq 0 ]; then
  # delete old assets only roughly 1/30 times
  # deleting old assets can break the site for people currently on it
  # but it's also good to keep things tidy
  aws s3 rm --recursive s3://stencil-rgst-io/assets/
  aws s3 rm --recursive --exclude "*" --include "*.html" s3://stencil-rgst-io/
fi

exec aws s3 cp --recursive .vitepress/dist s3://stencil-rgst-io/
