name: linters
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  check-generated-files-and-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          experimental: true
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Setup prettier
        run: bun install
      - run: mise run generate fmt
      - name: Check for changes
        run: |-
          git diff --exit-code HEAD || \
            ( echo \
              && echo "Formatting issues or stale documentation found. Please run 'mise run generate fmt'." \
              && exit 1)

  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          experimental: true
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Retrieve golangci-lint version
        run: |
          echo "version=$(mise current golangci-lint)" >> "$GITHUB_OUTPUT"
        id: golangci_lint
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v${{ steps.golangci_lint.outputs.version }}
          args: --timeout=30m
